In [2]:
import numpy as np

ar = np.array([1,2,3,4])
print(ar,type(ar))

[1 2 3 4] <class 'numpy.ndarray'>


In [3]:
li = [1,2,3,4,5]

print(type(li),li)

<class 'list'> [1, 2, 3, 4, 5]


# %timeit

In [4]:
%timeit [j**4 for j in range(1,9)]


3.96 µs ± 92.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [5]:
import numpy as np

%timeit np.arange(1,9)**4

3.44 µs ± 49.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [9]:
import numpy as np

ar = np.array([1,2,3,4])
print(ar)
print(ar.ndim)

[1 2 3 4]
1


# Array

In [11]:
ar_two = np.array([[1,2,3,4],[1,5,6,7]])

print(ar_two)
print(ar_two.ndim)


[[1 2 3 4]
 [1 5 6 7]]
2


In [13]:
ar_three = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,5]]])

print(ar_three)
print(ar_three.ndim)

[[[1 2 3 4]
  [4 5 6 7]
  [7 8 9 5]]]
3


In [15]:
import numpy as np

l = []
for i in range(1,5):
    int_inp = int(input("Enter the list:"))
    l.append(int_inp)

print(np.array(l))

Enter the list: 5
Enter the list: 6
Enter the list: 4
Enter the list: 7


[5 6 4 7]


In [18]:
arn = np.array([1,2,3],ndmin=11)
print(arn)
print(arn.ndim)

[[[[[[[[[[[1 2 3]]]]]]]]]]]
11


# zeros

In [24]:
import numpy as np

ar_zero = np.zeros(4)
ar_zero_two = np.zeros((3,4))

print(ar_zero)
print()
print(ar_zero_two)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# One

In [26]:
import numpy as np

ar_one = np.ones((4,4))
print(ar_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty

In [28]:
import numpy as np

ar_emp = np.empty((4,3))
print(ar_emp)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Diagonal

In [32]:
import numpy as np

ar_dia = np.eye(4)
ar_diag = np.eye(6,6)
print(ar_dia)
print()
print(ar_diag)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


# Linspace

In [36]:
import numpy as np

ar_li_spa = np.linspace(1,10,num = 5)

print(ar_li_spa)

[ 1.    3.25  5.5   7.75 10.  ]


# Random

# Rand()

In [38]:
import numpy as np

ar_ran = np.random.rand(4)

print(ar_ran)

[0.04966828 0.97426716 0.14494274 0.18060238]


# Randn()

In [40]:
import numpy as np

ar_randn = np.random.randn(4,4)
print(ar_randn)

[[-0.92398602 -0.06352341 -0.58558356 -0.82751191]
 [ 0.37605623 -0.48849252 -2.73698722 -0.21961908]
 [-0.96062247  0.15708114  0.52013484 -0.56715064]
 [ 1.37851883 -0.75164867  1.43877472 -0.41184143]]


# Ranf

In [43]:
import numpy as np

ar_ranf = np.random.ranf((4,4))
print(ar_ranf)

[[0.96612239 0.22058784 0.80868063 0.29614566]
 [0.67323643 0.42771395 0.46067745 0.3178903 ]
 [0.84152576 0.79387718 0.49755791 0.11558394]
 [0.73525532 0.43267767 0.00769466 0.29989788]]


# Randint

In [47]:
import numpy as np

ar_randint = np.random.randint(5,10,4)
print(ar_randint)

[7 8 6 7]


# Data type

In [51]:
import numpy as np

ar = np.array([1,2,3,4,5])

print(ar,ar.dtype)

[1 2 3 4 5] int32


In [52]:
ar_two = np.array([1.1,2.5,3.6])
print(ar_two,ar_two.dtype)

[1.1 2.5 3.6] float64


In [53]:
ar_str = np.array(['a','b','c'])
print(ar_str,ar_str.dtype)

['a' 'b' 'c'] <U1


In [54]:
ar_str = np.array(['a','b','c',1,2,3,4])
print(ar_str,ar_str.dtype)

['a' 'b' 'c' '1' '2' '3' '4'] <U11


In [57]:
import numpy as np

ar = np.array([1,2,3,4,5],dtype = np.int8)

print(ar,ar.dtype)

[1 2 3 4 5] int8


In [60]:
ar_fl = np.array(['a','b','c'],dtype = 'a')
print(ar_fl,ar_fl.dtype)

[b'a' b'b' b'c'] |S1


In [61]:
ar_two = np.array([1.1,2.5,3.6],dtype = 'f')
print(ar_two,ar_two.dtype)

[1.1 2.5 3.6] float32


In [66]:
ar_two = np.array([1.1,2.5,3.6])

x = np.float32(ar_two)
y = np.int_(ar_two)
print(x,x.dtype)
print(y,y.dtype)

[1.1 2.5 3.6] float32
[1 2 3] int32


In [70]:
ar_two = np.array([1,2,3,4])

x = ar_two.astype(float)
print(x)

[1. 2. 3. 4.]


# Arithmatics operation 

In [71]:
import numpy as np

ar_one = np.array([1,2,3,4,5])

x = ar_one + 3

print(x)

[4 5 6 7 8]


In [73]:
import numpy as np

ar_one = np.array([1,2,3,4,5])
ar_two = np.array([1,2,3,4,5])

x = np.add(ar_one,ar_two)

print(x)

[ 2  4  6  8 10]


In [74]:
ar_four = np.array([[1,2,3,4,5],[1,2,3,4,5]])
ar_five = np.array([[1,2,3,4,5],[1,2,3,4,5]])

y = np.add(ar_four,ar_five)

print(y)


[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [75]:
import numpy as np

ar_one = np.array([1,2,3,4,5])
ar_two = np.array([1,2,3,4,5])

x = (ar_one -ar_two)

print(x)

[0 0 0 0 0]


In [77]:
import numpy as np

ar_one = np.array([1,2,3,4,5,6,7,8,9,10])

x = np.reciprocal(ar_one)

print(x)

[1 0 0 0 0 0 0 0 0 0]


# Arithmatic function

In [3]:
import numpy as np

var = np.array([9,8,4,5,6,7,2])
print(np.min(var),np.argmin(var))
print(np.max(var),np.argmax(var))

2 6
9 0


In [6]:
import numpy as np

var = np.array([[9,8,4,5,6,7,2],[9,8,4,5,6,7,2]])

print(np.min(var,axis = 1))
print(np.max(var,axis = 1))

[2 2]
[9 9]


In [9]:
import numpy as np

var = np.array([9,8,4,5,6,7,2])

print(np.sin(var))
print()
print(np.cos(var))
print()
print(np.cumsum(var))

[ 0.41211849  0.98935825 -0.7568025  -0.95892427 -0.2794155   0.6569866
  0.90929743]

[-0.91113026 -0.14550003 -0.65364362  0.28366219  0.96017029  0.75390225
 -0.41614684]

[ 9 17 21 26 32 39 41]


# Shape

In [10]:
import numpy as np 

var = np.array([[1,2,3,4,5],[5,6,7,8,9]])

print(var.shape)

(2, 5)


In [12]:
import numpy as np 

var = np.array([1,2,3,4,5],ndmin = 4)

print(var.shape)

(1, 1, 1, 5)


In [13]:
import numpy as np 

var = np.array([1,2,3,4,5,6])

print(var.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [16]:
import numpy as np 

var = np.array([1,2,3,4,5,6,4,5,6,7,8,9])

print(var.reshape(2,3,2))


[[[1 2]
  [3 4]
  [5 6]]

 [[4 5]
  [6 7]
  [8 9]]]
1


In [17]:
import numpy as np 

var = np.array([1,2,3,4,5,6,4,5,6,7,8,9])

print(var.reshape(2,3,2))

x = var.reshape(-1)
print(x)

[[[1 2]
  [3 4]
  [5 6]]

 [[4 5]
  [6 7]
  [8 9]]]
[1 2 3 4 5 6 4 5 6 7 8 9]


# Brodcasting 

In [18]:
import numpy as np

var = np.array([1,2,3])
var_two = np.array([[1],[2]])

print(var + var_two)

[[2 3 4]
 [3 4 5]]


In [19]:
var_three = np.array([[1],[2]])
var_four = np.array([[1,2,3],[1,2,3]])

print(var_three + var_four)

[[2 3 4]
 [3 4 5]]


# Indexing 

In [20]:
import numpy as np

var = np.array([1,2,3,4])

print(var[1])

2


In [21]:
import numpy as np

var = np.array([[1,2,3,4],[4,5,6,7]])

print(var[1,2])

6


In [23]:
import numpy as np

var = np.array([[[1,2,3,4],[4,5,6,7],[5,8,9,7]]])

print(var[0,0,1])

2


# Slicing

In [25]:
import numpy as np

var = np.array([[1,2,3,4],[4,5,6,7]])

print(var[0,2:])

[3 4]


In [26]:
import numpy as np

var = np.array([[[1,2,3,4],[4,5,6,7],[5,8,9,7]]])

print(var[0,0,1:3])

[2 3]


In [27]:
import numpy as np

var = np.array([[[1,2,3,4],[4,5,6,7],[5,8,9,7]]])

print(var[0,0,::2])

[1 3]


# terating numpy

In [28]:
import numpy as np

var = np.array([1,2,4,5])

for i in var:
    print(i)


1
2
4
5


In [31]:
import numpy as np

var = np.array([[1,2,4,5],[4,5,6,7]])

for i in var:
    for j in i:
        print(j)

1
2
4
5
4
5
6
7


In [33]:
import numpy as np

var = np.array([[[1,2,4,5],[4,5,6,7],[5,8,2,6]]])

for i in var:
    for j in i:
        for k in j:
            print(k)

1
2
4
5
4
5
6
7
5
8
2
6


In [36]:
import numpy as np

var = np.array([[[1,2,4,5],[4,5,6,7],[5,8,2,6]]])

for i in np.nditer(var):
    
    print(i)

1
2
4
5
4
5
6
7
5
8
2
6


In [37]:
import numpy as np

var = np.array([[[1,2,4,5],[4,5,6,7],[5,8,2,6]]])

for i in np.ndenumerate(var):
    
    print(i)

((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 0, 2), 4)
((0, 0, 3), 5)
((0, 1, 0), 4)
((0, 1, 1), 5)
((0, 1, 2), 6)
((0, 1, 3), 7)
((0, 2, 0), 5)
((0, 2, 1), 8)
((0, 2, 2), 2)
((0, 2, 3), 6)


# Copy vs View

In [39]:
import numpy as np

var = np.array([1,2,3,4])
x = var.copy()

var[1] = 20

print("var",var)
print("copy",x)

var [ 1 20  3  4]
copy [1 2 3 4]


In [41]:
import numpy as np

var = np.array([1,2,3,4])
x = var.view()

var[1] = 20

print("var",var)
print("view",x)

var [ 1 20  3  4]
view [ 1 20  3  4]


# joining and split numpy

In [13]:
import numpy as np

var = np.array([[1,2,3],[4,5,6]])
var_two = np.array([[4,5,6],[7,8,9]])

x = np.concatenate((var , var_two),axis = 0)

print(x)

[[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]


In [11]:
import numpy as np

var = np.array([1,2,3,4,5,6])
var_two = np.array([4,5,6,7,8,9])

x = np.concatenate((var , var_two))

print(x)

[1 2 3 4 5 6 4 5 6 7 8 9]


In [17]:
import numpy as np

var = np.array([1,2,3,4,5,6])
var_two = np.array([4,5,6,7,8,9])

x = np.stack((var,var_two))
y = np.hstack((var,var_two))
z = np.vstack((var,var_two))
b = np.dstack((var,var_two))

print(x)
print()
print(y)
print()
print(z)
print()
print(b)

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]

[1 2 3 4 5 6 4 5 6 7 8 9]

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]

[[[1 4]
  [2 5]
  [3 6]
  [4 7]
  [5 8]
  [6 9]]]


# Split numpy

In [19]:
import numpy as np

var = np.array([[1,2,3],[4,5,6]])

x = np.array_split(var,3)
print(var)
print()
print(x)



[[1 2 3]
 [4 5 6]]

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]


# Search

In [24]:
import numpy as np

var = np.array([1,2,4,5,6,2,4,5,1,3,5,4,8,9,7,5,7,4,6,2,1])

ar = np.where(var==2)
print(ar)

(array([ 1,  5, 19], dtype=int64),)


# Search short

In [29]:
import numpy as np

var = np.array([1,2,4,5,6,8,10])
ar = np.searchsorted(var,9)

print(ar)

6


# Sorted 

In [31]:
import numpy as np

var = np.array([5,4,2,1,8,7,9,4,2,1,3,5,6,4])
ar = np.sort(var)

print(ar)

[1 1 2 2 3 4 4 4 5 5 6 7 8 9]


In [32]:
import numpy as np

var = np.array(['a','c','z','x'])
ar = np.sort(var)

print(ar)

['a' 'c' 'x' 'z']


In [34]:
import numpy as np

var = np.array(['a','c','z','x'])
ar = [True,False,True,True]
new = var[ar]

print(new)

['a' 'z' 'x']


# shuffle

In [38]:
import numpy as np

var = np.array([1,2,3,4,5])

np.random.shuffle(var)
print(var)

[5 3 4 2 1]


# unique

In [45]:
import numpy as np

var = np.array([5,1,4,2,3,1,5,4,3,2,1,5])

x = np.unique(var,return_index = True,return_counts = True)
print(x)

(array([1, 2, 3, 4, 5]), array([1, 3, 4, 2, 0], dtype=int64), array([3, 2, 2, 2, 3], dtype=int64))


# resize

In [42]:
import numpy as np

var = np.array([5,1,4,2,3,1])

x = np.resize(var,(2,3))
print(x)

[[5 1 4]
 [2 3 1]]


# flatten

In [54]:
import numpy as np

var = np.array([5,1,4,2,3,1])

x = np.resize(var,(2,3))

print(x)
print()
print(x.flatten(order = "c"))
print(x.ravel(order = "f"))

[[5 1 4]
 [2 3 1]]

[5 1 4 2 3 1]
[5 2 1 3 4 1]


# Insert

In [55]:
import numpy as np

var = np.array([1,2,4,5])

x = np.insert(var,2,3)

print(x)

[1 2 3 4 5]


In [57]:
import numpy as np

var = np.array([[1,2,4,5],[1,2,4,5]])

x = np.insert(var,2,3,axis = 0)

print(x)

[[1 2 4 5]
 [1 2 4 5]
 [3 3 3 3]]


In [59]:
import numpy as np

var = np.array([1,2,4,5])

x = np.append(var,3)

print(x)

[1 2 4 5 3]


In [62]:
import numpy as np

var = np.array([[1,2,4,5],[1,2,4,5]])

x = np.append(var,[[3,4,5,7]],axis = 0)

print(x)

[[1 2 4 5]
 [1 2 4 5]
 [3 4 5 7]]


In [63]:
import numpy as np

var = np.array([1,2,4,5])

x = np.delete(var,3)

print(x)

[1 2 4]


In [64]:
import numpy as np

var = np.array([[1,2,4,5],[1,2,4,5]])

x = np.delete(var,[[3,4,5,7]],axis = 0)

print(x)

IndexError: index 3 is out of bounds for axis 0 with size 2